name: foo
description: "Foo"

inputs:
  bar:
    description: "Bar"
    required: false
    default: "baz"

runs:
  using: "composite"
  steps:
    - name: Step referencing action
      uses: actions/checkout@v4
      id: checkout
      env:
        FOO_VAL: ${{ inputs.bar == 'baz' }} # true
      if: ${{ inputs.bar == 'baz' }} # false, so this step is always skipped

    - name: Debug
      run: |
        echo "RESULT: ${{ steps.checkout.conclusion }}"
        echo "FOO_VAL: $FOO_VAL"
      shell: bash
      env:
        FOO_VAL: ${{ inputs.bar == 'baz' }} # true
      if: ${{ inputs.bar == 'baz' }} # true as well
